package gradjanibrzogbroda.backend.domain;

public enum TipAktivnosti {
    PREUZETA_PORUDZBINA, PREUZETO_JELO, PRIPREMLJENO_JELO, DOSTAVLJENO_JELO,
    PRIPREMLJENO_PICE, DOSTAVLJENO_PICE, DOSTAVLJENA_PORUDZBINA, NAPLACENA_PORUDZBINA
}
